INSERT INTO warehouse_categories( name, description) VALUES ('CARNE', 'Todo tipo de carnes');
INSERT INTO warehouse_categories( name, description) VALUES ('PESCADO', 'Todo tipo de pescados');
INSERT INTO warehouse_categories( name, description) VALUES ('VERDURAS', 'Todo tipo de verdudas');
INSERT INTO warehouse_categories( name, description) VALUES ('LACTEOS', 'leche, yoghures');
INSERT INTO warehouse_categories( name, description) VALUES ('FRUTAS', 'Las golosinas de la naturaleza');
INSERT INTO warehouse_categories( name, description) VALUES ('BEBIDAS', 'Cosas de beber');
INSERT INTO warehouse_sub_categories( name, description) VALUES ('POLLO', 'Subcatergoria 1');
INSERT INTO warehouse_sub_categories( name, description) VALUES ('TERNERA', 'Subcatergoria 2');
INSERT INTO warehouse_sub_categories( name, description) VALUES ('EMPERADOR', 'Subcatergoria 3');
INSERT INTO warehouse_sub_categories( name, description) VALUES ('LECHE', 'Subcatergoria 4');
INSERT INTO warehouse_sub_categories( name, description) VALUES ('PLATANOS', 'Subcatergoria 5');
INSERT INTO warehouse_sub_categories( name, description) VALUES ('NARANJAS', 'Subcatergoria 6');
INSERT INTO warehouse_sub_categories( name, description) VALUES ('AGUA', 'Subcatergoria 7');